# This playbook installs all configuration files in the server's root.
#
# Copyright (c) 2013 Fabian Affolter <fabian@affolter-engineering.ch>
#
# Licensed under CC BY 3.0. All rights reserved.
#
---
- name: create the directory for the configuration files
  file: path=/var/www/lighttpd/config
        mode=0755
        state=directory

- name: copy the configuration files
  template: src=../files/{{ item }}.j2
        dest=/var/www/lighttpd/config/{{ item }}.php
        owner=lighttpd
        group=lighttpd
        mode=0644
  with_items: config
