# This playbook installs css files in the server's root.
#
# Copyright (c) 2013 Fabian Affolter <fabian@affolter-engineering.ch>
#
# Licensed under CC BY 3.0. All rights reserved.
#
---
- name: create the directory for the css files
  file: path=/var/www/lighttpd/css
        mode=0755
        state=directory

- name: copy the css files
  copy: src=../../css/{{ item }}
        dest=/var/www/lighttpd/css/{{ item }}
        owner=lighttpd
        group=lighttpd
        mode=0644
  with_items: css
