# This playbook install the mosquitto broker (http://mosquitto.org).
#
# Copyright (c) 2013 Fabian Affolter <fabian@affolter-engineering.ch>
#
# Licensed under CC BY 3.0. All rights reserved.
#
---
- name: install mosquitto package
  yum: pkg={{ item }}
       state=present 
  with_items:
    - mosquitto
    - mosquitto-devel

- name: configure firewall, allow traffic to port 1883
  firewalld: port=1883/tcp
             permanent=true
             state=enabled

- name: start mosquitto
  service: name=mosquitto
           state=running
           enabled=yes

# PHP extension
# ftp://rpmfind.net/linux/remi/fedora/20/remi/x86_64/php-pecl-mosquitto-0.2.1-1.fc20.remi.5.5.x86_64.rpm
