# This playbook install a simple file for displaying details about the PHP
# installation.
#
# Copyright (c) 2013 Fabian Affolter <fabian@affolter-engineering.ch>
#
# Licensed under CC BY 3.0. All rights reserved.
#
---
- name: copy the phpinfo file
  copy: src=files/phpinfo.j2
        dest=/var/www/lighttpd/phpinfo.php
        owner=lighttpd
        group=lighttpd
        mode=0644
