# This playbook installs static files in the server's root.
#
# Copyright (c) 2013 Fabian Affolter <fabian@affolter-engineering.ch>
#
# Licensed under CC BY 3.0. All rights reserved.
#
---
- name: copy the static files
  template: src=../files/{{ item }}.j2
            dest=/var/www/lighttpd/{{ item }}.txt
            owner=lighttpd
            group=lighttpd
            mode=0644
  with_items: static
