# This playbook deploy the content of the webshop to the web server.
#
# Copyright (c) 2013 Fabian Affolter <fabian@affolter-engineering.ch>
#
# Licensed under CC BY 3.0. All rights reserved.
#
# Usage: sudo ansible-playbook setup.yml
# 
---
- hosts: webshop
  user: root
  vars:
    - css: [webshop.css]
    - html: [index.html]
    - script: [menu.php, header.php, footer.php, helpers.php,  add-process.php, 
              openweathermap.php, send-msg.php, signup-process.php, 
              get-products.php, login-process.php, edit-process.php,
              delete-process.php, recieve-msg.php,
              leaflet-osm.js, cookie.php, details.php, register-process.php,
              send-mail.php, page-elements.php, Product.php, ShoppingCart.php,
              add-product-process.php, pdf-cart.php, pdf-spec.php, l10n.php]
    - php: [index.php, index1.php, add.php, customers.php, graphics.php,
            products.php, product.php, json.php, cart.php, billing.php,
            about.php, register.php, billing.php, admin.php, send-test-msg.php,
            tables.php, customers.php, users.php, cookies.php, l10n.php, 
            sessions.php, master.tpl.php, terms.php, edit.php, logout.php,
            add-product.php, overview-products.php, login.php]
    - config: [dbconnect, variables]
    - static: [company]
    - logos: [logo.png]
    - l10n: [de_CH, fr_FR, en_US]
    - images: [default.png, black.png, blue.png, red.png, white.png]
  vars_files:
    - variables/sensitive.yml
    - variables/common.yml

  tasks:
#    - include: tasks/images.yml
#    - include: tasks/css.yml
#    - include: tasks/html.yml ## This playbook is no longer needed.
    - include: tasks/static.yml
#    - include: tasks/savant.yml
#    - include: tasks/fpdf.yml
    - include: tasks/script.yml
    - include: tasks/php.yml
#    - include: tasks/l10n.yml
#    - include: tasks/config.yml
