# This playbook deploy the content of the webshop to the web server.
#
# Copyright (c) 2013 Fabian Affolter <fabian@affolter-engineering.ch>
#
# Licensed under CC BY 3.0. All rights reserved.
#
# Usage: sudo ansible-playbook setup.yml
# 
---
- hosts: webshop
  user: root
  vars:
    - css: [webshop.css]
    - html: [index.html]
    - php: [index.php, products.php, product.php, about.php, menu.php,
            header.php, footer.php, helpers.php, variables.php]
    - static: [company.txt]
    - logos: [logo.png]
    - images: [default.png]
  vars_files:
    - variables/sensitive.yml
    - variables/common.yml

  tasks:
    - include: tasks/images.yml
    - include: tasks/css.yml
#    - include: tasks/html.yml ## This playbook is no longer needed.
    - include: tasks/static.yml
    - include: tasks/php.yml
