#!/bin/bash
#
# shop-virt - Creator for a libvirt-based virtual machine for a shop.
#
# Copyright (c) 2012-2013 Fabian Affolter <fab@fedoraproject.org>
#
# Licensed under GPLv2+. All rights reserved.
#
cat <<END_ENTRY >> webshop.ks
# Minimal Kickstart file for the Fedora Security Lab test bench
# Installation, not an upgrade
install

# No graphical things needed
skipx
text

# Language
lang en_US.UTF-8

# Kexboard setup
keyboard sg-latin1
#keyboard us

# Networking
network --onboot yes --device eth0 --bootproto dhcp --ipv6 auto --hostname webshop

# Authentication
auth --enableshadow --passalgo=sha512
rootpw webshop

# Services, SELinux and firewall
firewall --enabled --ssh
services --enabled network,sshd
selinux --enforcing
#firstboot --disable
logging --level=info

# Time zone
timezone Europe/Zurich

# Disk setup
zerombr
bootloader --location=mbr --append="rd_NO_PLYMOUTH"
ignoredisk --only-use=vda
clearpart --none --initlabel --drives=vda
autopart

poweroff

%packages
@core
chrony
bash-completion
tar
unzip
%end
END_ENTRY

sudo virt-install \
    --name webshop \
    --os-variant fedora20 \
    --ram 1024 \
    --disk /var/lib/libvirt/images/webshop.img,size=8 \
    --location ftp://ftp-stud.hs-esslingen.de/pub/fedora/linux/releases/20/Fedora/x86_64/os \
    --initrd-inject webshop.ks \
    --extra-args "ks=file:webshop.ks" \
    --noautoconsole \
    --autostart \
    --network=network:default \
    --mac=52:52:99:99:99:99

rm webshop.ks
